sudo: false
language: python
notifications:
  email: false
python:
  - 2.6
  - 2.7
before_install:
  - rm README.rst; touch README.rst  # fails
  - if [[ -f rnd_requirements.txt ]]; then pip install -r rnd_requirements.txt; fi
  - pip install -r tests/requirements.txt
script:
  make test
after_success:
  codecov
