sudo: false
language: python
notifications:
  email: false
env:
  global:
python:
  - 2.6
  - 2.7
install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install ordereddict; fi
  - pip install git+https://github.com/chfw/pyexcel-io/archive/master.zip
  - pip install git+https://github.com/chfw/pyexcel/archive/master.zip
  - pip install git+https://github.com/chfw/pyexcl-xls/archive/master.zip
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt --use-mirrors
script:
  make test
after_success:
  codecov
