language: python
notifications:
  email: false
env:
  global:
python:
  - 2.6
  - 2.7
install:
  - python setup.py install
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install ordereddict; fi
  - pip install git+https://github.com/chfw/pyexcel.git
  - pip install -r tests/requirements.txt --use-mirrors
script:
  make test
after_success:
  codecov
